title: Open Government Products - Best Practices
remote_theme: opendocsg/opendoc-theme@s3pdf
timezone: Asia/Singapore
repository: opendocsg/opendoc-ogp-best-practices
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
offline: false
# google_analytics: --------> COPY GA ID HERE
document_order:
  - Development
  - Deployment

styling_options:
  primary_brand_color: '#276ef1'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://open.gov.sg/contact-us/
