title: Open Government Products - Best Practices
remote_theme: opendocsg/opendoc-theme@v2
timezone: Asia/Singapore
repository: opendocsg/opendoc-opengovsg-best-practices
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
# google_analytics: --------> COPY GA ID HERE
order:
  - Open Government Products - Best Practices
  - Node.js Developer Setup
  - Linting
  - Using GitHub
  - AWS Best Practices
  - Working with Nectar

styling_options:
  primary_brand_color: '#276ef1'
  logo_path: /assets/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://open.gov.sg/contact-us/
